/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import javax.swing.JOptionPane;

import java.sql.*;


public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }
    
    void Visibility(Boolean b){
        lblname.setVisible(b);
        lbladdress.setVisible(b);
        tfname.setVisible(b);
        tfaddress.setVisible(b);
        if(b){
            lblmain.setText("Registre-se");
            btnlogin.setText("Já possui uma conta?");
        }else{
             lblmain.setText("Login");
            btnlogin.setText("Login");
        }
        
    }
    
    
    void LoginCall(String usr, String pswd){
        boolean flag=false;
        try{
            Class.forName("java.sql.Driver");            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/logins","root", "password");
            Statement stmt = conn.createStatement();
            String qrry = "select * from employ where email=\"" + usr +"\" and password=\"" + pswd +"\" ;";
            ResultSet rs = stmt.executeQuery(qrry);
            while(rs.next()){
                flag=true;
            }
            if(flag){
                JOptionPane.showMessageDialog(null, "Logado com sucesso!");                
                dispose();
                Home hpage = new Home();
                hpage.show();
                
            }else{
                JOptionPane.showMessageDialog(null, "Inválido user/password");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error in connectivity" + ex);
        }
    }

    
    
    
    
    
    
    

    void RegisterCall(String email, String password, String name, String address){
         try{
            Class.forName("java.sql.Driver");
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/logins","root", "password");
            Statement stmt = conn.createStatement();
            String qrry = "insert into employ values (" 
                   + "\"" + email + "\","
                   + "\"" + password + "\","
                   + "\"" + name + "\","
                   + "\"" + address + "\""
                   + ")";
            
            
            
            stmt.executeUpdate(qrry);
           
            stmt.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Registrado com sucesso!");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"705Error in connectivity" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblmain = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfEmailLogin = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfPasswordLogin = new javax.swing.JPasswordField();
        lblname = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        lbladdress = new javax.swing.JPanel();
        tfaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(48, 136, 176));
        jPanel3.setMinimumSize(new java.awt.Dimension(960, 460));
        jPanel3.setPreferredSize(new java.awt.Dimension(960, 650));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Registre-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 210, 70));

        btnlogin.setText("Já possui uma conta?");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 230, 70));

        jLabel3.setBackground(new java.awt.Color(173, 66, 31));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(203, 23, 23));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 20, -1));

        lblmain.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        lblmain.setForeground(new java.awt.Color(39, 20, 20));
        lblmain.setText("Registre-se");
        jPanel3.add(lblmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 170, 50));

        jPanel4.setBackground(new java.awt.Color(48, 136, 176));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 4, 4));
        jLabel1.setText("Email:");
        jLabel1.setName(""); // NOI18N

        tfEmailLogin.setForeground(new java.awt.Color(180, 175, 203));
        tfEmailLogin.setText("Digite seu email...");
        tfEmailLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailLoginFocusGained(evt);
            }
        });
        tfEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(tfEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmailLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 360, 40));

        jPanel5.setBackground(new java.awt.Color(48, 136, 176));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 4, 4));
        jLabel2.setText("Senha:");

        tfPasswordLogin.setForeground(new java.awt.Color(180, 175, 203));
        tfPasswordLogin.setText("Password");
        tfPasswordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordLoginFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(tfPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPasswordLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 360, 40));

        lblname.setBackground(new java.awt.Color(48, 136, 176));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 4, 4));
        jLabel5.setText("Nome:");

        javax.swing.GroupLayout lblnameLayout = new javax.swing.GroupLayout(lblname);
        lblname.setLayout(lblnameLayout);
        lblnameLayout.setHorizontalGroup(
            lblnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblnameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblnameLayout.setVerticalGroup(
            lblnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 380, 40));

        lbladdress.setBackground(new java.awt.Color(48, 136, 176));

        tfaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaddressActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 4, 4));
        jLabel4.setText("Endereço:");

        javax.swing.GroupLayout lbladdressLayout = new javax.swing.GroupLayout(lbladdress);
        lbladdress.setLayout(lbladdressLayout);
        lbladdressLayout.setHorizontalGroup(
            lbladdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbladdressLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        lbladdressLayout.setVerticalGroup(
            lbladdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbladdressLayout.createSequentialGroup()
                .addGroup(lbladdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 410, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        if(lblmain.getText().equals("Registre-se")){
            if(tfEmailLogin.getText().length()==0 || tfPasswordLogin.getText().length()==0 || tfname.getText().length()==0 || tfaddress.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }else{
                RegisterCall(tfEmailLogin.getText(), tfPasswordLogin.getText(), tfname.getText(), tfaddress.getText());     
            }
        
        
     
       }
        Visibility(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tfEmailLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailLoginFocusGained
        tfEmailLogin.setText("");
    }//GEN-LAST:event_tfEmailLoginFocusGained

    private void tfPasswordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordLoginFocusGained
        tfPasswordLogin.setText("");
    }//GEN-LAST:event_tfPasswordLoginFocusGained

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        
        
        
        
        if(lblmain.getText().equals("Login")){            
            if(tfEmailLogin.getText().length()==0 || tfPasswordLogin.getText().length()==0){            
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }else{
                LoginCall(tfEmailLogin.getText(), tfPasswordLogin.getText());
            }
         
        }Visibility(false);
        
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void tfaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel lbladdress;
    private javax.swing.JLabel lblmain;
    private javax.swing.JPanel lblname;
    private javax.swing.JTextField tfEmailLogin;
    private javax.swing.JPasswordField tfPasswordLogin;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables
}
